spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-mcms-open?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
